[versions]
minecraft = "1.21.5-R0.1-SNAPSHOT"

[plugins]
gradle-plugin-publish = { id = "com.gradle.plugin-publish", version = "1.3.1" }

[libraries]
gson = { module = "com.google.code.gson:gson", version = "2.12.1" }
spigot-api = { module = "org.spigotmc:spigot-api", version.ref = "minecraft" }
